//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frete4U.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cd_prestador
    {
        public tb_cd_prestador()
        {
            this.tb_cd_cidades = new HashSet<tb_cd_cidades>();
            this.tb_cd_tipo_entrega = new HashSet<tb_cd_tipo_entrega>();
        }
    
        public int cod_prestador { get; set; }
        public string Id { get; set; }
        public string nome { get; set; }
        public string nomeEmpresa { get; set; }
        public Nullable<decimal> CPF { get; set; }
        public Nullable<decimal> CNPJ { get; set; }
        public string logradouro { get; set; }
        public Nullable<decimal> numeroEndereco { get; set; }
        public string bairro { get; set; }
        public string Complemento { get; set; }
        public Nullable<decimal> cod_cidade { get; set; }
        public Nullable<decimal> cod_estado { get; set; }
    
        public virtual ICollection<tb_cd_cidades> tb_cd_cidades { get; set; }
        public virtual ICollection<tb_cd_tipo_entrega> tb_cd_tipo_entrega { get; set; }
    }
}
