//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frete4U.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cd_transporte
    {
        public int cod_transporte { get; set; }
        public string descricao { get; set; }
        public int cod_entrega { get; set; }
    
        public virtual tb_cd_tipo_entrega tb_cd_tipo_entrega { get; set; }
    }
}
