//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frete4U.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_cd_cidades
    {
        public tb_cd_cidades()
        {
            this.tb_cd_prestador = new HashSet<tb_cd_prestador>();
        }
    
        public decimal cod_cidade { get; set; }
               
        [Display(Name = "Cidade")]
        public string nom_cidade { get; set; }

        public Nullable<decimal> cod_estado { get; set; }
    
        public virtual tb_cd_estados tb_cd_estados { get; set; }
        public virtual ICollection<tb_cd_prestador> tb_cd_prestador { get; set; }
    }
}
