//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frete4U.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cd_estados
    {
        public tb_cd_estados()
        {
            this.tb_cd_cidades = new HashSet<tb_cd_cidades>();
        }
    
        public decimal cod_estado { get; set; }
        public string nom_estado { get; set; }
        public string uf { get; set; }
    
        public virtual ICollection<tb_cd_cidades> tb_cd_cidades { get; set; }
    }
}
